merah="\e[31m"
kuning="\e[33m"
hijau="\e[32m"
biru="\e[34m"
UL="\e[4m"
bold="\e[1m"
italic="\e[3m"
reset="\e[m"
echo -e "$bold$italic$biru"
echo "    ╒═╗╒════╗╒═⸜ ⸝═╗╒════╗╒═╗ ╒═╗╒═╗  ╒═⸜ ⸝═╗╒═══╗╒════╗╒════╗╒═╗ ╒═╗"
echo "      ║  ╓  ║  ⧹   ║  ╓  ║  ║   ║  ║    ⧹   ║  ╓ ╜  ╓  ║  ╓  ║  ║   ║"
echo "      ║  ╚═ ║      ║  ╚═ ║  ║   ║  ║        ║  ╚═╗  ╚═ ║  ╚═ ║  ╚═╛ ║"
echo "╒═╗   ║  ╓  ║  ║ ᜶ ║  ╓ ⟪_  ║   ║  ║    ║ ᜶ ║  ╓ ╜  ╓ ⟪_  ╓  ║  ╓   ║"
echo "  ╚═╛ ║  ║  ║  ║   ║  ╚═ ║  ╚═╛ ║  ╚═╗  ║   ║  ╚═╗  ║  ║  ║  ║  ║   ║"
echo -e "$reset$bold$merah====================>>($hijau https://jambulmerah.dev $merah)<<===================$reset\n"
